### ISSUE TITLE
Error running app

### ISSUE THREAD

**Issue by tweetylly** [chrieke/prettymapp#25]
Not able to access to the app.

It shows 'Oh no.
Error running app. If this keeps happening, please [contact support](https://github.com/chrieke/prettymapp/issues/new).'

Any thoughts? I tried using different browsers but did not help.

**Comment by jpriebe** [comment]
It's happening again -- maybe the post on Hacker News is overloading the app?

**Comment by chrieke** [comment]
Thanks! Testing, but so far locally with new env it works :/

**Comment by chrieke** [comment]
Yeah seems to just be overwhelmed. One positive out of this, it's now available under both the old url and prettymapp.streamlit.com
