### ISSUE TITLE
Error running app. If this keeps happening, please contact support.

### ISSUE THREAD

**Issue by gertvervaet** [chrieke/prettymapp#31]
I tried to start the prettymapp app on streamlit using https://prettymapp.streamlit.app/ and get this error: 

> Error running app. If this keeps happening, please [contact support](https://github.com/chrieke/prettymapp/issues/new).

Both on Brave and in Firefox

**Comment by chrieke** [comment]
Thank you, hope it becomes useable again soon, also see https://github.com/chrieke/prettymapp/issues/32

Closing.

**Comment by Razworld00** [comment]
Link can't open app - give an error
