### ISSUE TITLE
https://prettymapp.streamlit.app/

### ISSUE THREAD

**Issue by marcolino** [chrieke/prettymapp#32]
Oh no.
Error running app. If this keeps happening, please [contact support](https://github.com/chrieke/prettymapp/issues/new).

**Comment by falkecarlsen** [comment]
Might be hug-of-death from Hackernews https://news.ycombinator.com/item?id=37222823

**Comment by chrieke** [comment]
Yeah not much I can do right now, when restarting or deleting&creating the app again it goes down after 3 seconds, something is off.

Afaik the streamlit folks already increased the app memory.

**Comment by jxpsert** [comment]
Duplicate of #30
