### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by djsavvy** [chrieke/prettymapp#33]
Looks like it's MIT licensed on PyPi: https://pypi.org/project/prettymapp/

![image](https://github.com/chrieke/prettymapp/assets/26914352/da6bd4b9-618b-41c4-ba30-e1905bb9b99b)

Could the GitHub repo be updated with the license?

**Comment by chrieke** [comment]
Added [MIT licence](https://github.com/chrieke/prettymapp/blob/main/LICENSE), thanks for the ping!

**Comment by djsavvy** [comment]
Thanks! Incredible project BTW, been having a lot of fun playing with a local copy :)
