### ISSUE TITLE
Requirements.txt updates

### ISSUE THREAD

**Issue by thomas75007** [chrieke/prettymapp#4]
Recreating the requirements from my pc I get:

attrs==21.4.0
certifi==2022.6.15
charset-normalizer==2.1.0
click==8.1.3
click-plugins==1.1.1
cligj==0.7.2
cycler==0.11.0
Fiona==1.8.21
fonttools==4.34.4
geopandas==0.11.1
idna==3.3
kiwisolver==1.4.4
matplotlib==3.5.2
munch==2.5.0
networkx==2.8.5
numpy==1.23.1
osmnx==1.2.1
packaging==21.3
pandas==1.4.3
Pillow==9.2.0
prettymapp==0.0.1
pyparsing==3.0.9
pyproj==3.3.1
python-dateutil==2.8.2
pytz==2022.1
requests==2.28.1
Rtree==1.0.0
Shapely==1.8.2
six==1.16.0
urllib3==1.26.11

Please let me know if it is correct.
Best regards

**Comment by chrieke** [comment]
Hi thomas, the prettymapp Python package only requires osmnx, which installs some subdependencies, probably what you have in the list above. What seems to be the issue?

**Comment by thomas75007** [comment]
Hi Christoph,
When I tried to install your app (pip install git+...) an error occured
saying that the wheel package was not found.
To solve this, I needed to install wheel before installing your git.
And now it works perfectly.
That's why I've thought that some dependencies were missing in the
requirements file.


Le mar. 26 juil. 2022 à 23:20, Christoph Rieke ***@***.***> a
écrit :

**Comment by viperfx** [comment]
@chrieke perhaps it's a good idea to pin the version of osmnx?

**Comment by chrieke** [comment]
Tested in new environment. It installs osmnx at 1.2.2, example works. 
@viperfx Will pin it at 1.2.2 now.
@thomas75007 [osmnx](https://github.com/gboeing/osmnx/blob/main/requirements.txt) doesnt pin its packages to an exact version, comparsion isn't possible. But, the current installation works.
