### ISSUE TITLE
feature req: Plot from an osm file

### ISSUE THREAD

**Issue by TheStarAlight** [chrieke/prettymapp#47]
Hi! The prettymapp & prettymaps are great projects that plot impressive maps 🥰
Now I need to make a map plot using prettymapp, and I prefer to download the osm file in advance, because the network is not good and I prefer making all the resources local, also, the osm file I want to plot is very big (~80 MB). I wonder if prettymapp can add an interface to pass in the osm file path and parse it offline? Or, may I know the walkaround in current situation? Thank you!

**Comment by chrieke** [comment]
Hi @TheStarAlight How do you download the file and in what format do you have it?

**Comment by TheStarAlight** [comment]
Hello! I downloaded it using the overpass API: `https://overpass-api.de/api/map?bbox=118.4862,29.3295,119.2937,29.7644`, and it is an osm file. I tried to parse it into GeoDataFrame and pass to the plot function and it failed as expected...
```
g = ox.graph_from_xml("Qiandaohu.osm")
df = ox.graph_to_gdfs(g, nodes=False, edges=True)
plot = prettymaps.plot(df)
```
Sorry, new to GIS and I know nothing about it :(

**Comment by chrieke** [comment]
Will look into it. Not sure it will be added, but I was recently also thinking I'd love to have big local OSM file e.g. for a country and use the code anywhere for that country without the osmnx download.

**Comment by TheStarAlight** [comment]
@chrieke Thank you~🥰 But plotting a country's map seems very time-consuming, maybe we also need a scale level in the function argument.

**Comment by chrieke** [comment]
Hehe yeah sure, no I got what you want to achieve. It's just a related thought.

**Comment by chrieke** [comment]
Hey finally got around to check this out. It's actually pretty simple. I haven't added it to the library, but here is a working example:


This is the same code as the prettymapp osm module, just switching `osmnx.features.features_from_polygon` to `features_from_xml`.
```
from osmnx import settings
from osmnx.features import features_from_xml
from geopandas import clip, GeoDataFrame
from shapely.geometry import Polygon

from prettymapp.geo import explode_multigeometries
from prettymapp.settings import LC_SETTINGS


def get_osm_geometries_from_xml(xml_filepath: str, aoi: Polygon) -> GeoDataFrame:
    tags: dict = {}
    for d in LC_SETTINGS.values():  # type: ignore
        for k, v in d.items():  # type: ignore
            try:
                tags.setdefault(k, []).extend(v)
            except TypeError:  # e.g. "building": True
                tags[k] = v

    df = features_from_xml(xml_filepath, tags=tags)
    
    df = df.droplevel(level=0)
    df = df[~df.geometry.geom_type.isin(["Point", "MultiPoint"])]

    df = clip(df, aoi)
    df = explode_multigeometries(df)

    df["landcover_class"] = None
    for lc_class, osm_tags in LC_SETTINGS.items():
        tags_in_columns = list(set(osm_tags.keys()).intersection(list(df.columns)))  # type: ignore
        mask_lc_class = df[tags_in_columns].notna().sum(axis=1) != 0
        # Remove mask elements that belong to other subtag
        listed_osm_tags = {
            k: v
            for k, v in osm_tags.items()  # type: ignore
            if isinstance(v, list) and k in tags_in_columns
        }
        for tag, subtags in listed_osm_tags.items():
            mask_from_different_subtag = ~df[tag].isin(subtags) & df[tag].notna()
            mask_lc_class[mask_from_different_subtag] = False
        df.loc[mask_lc_class, "landcover_class"] = lc_class
    # Drop not assigned elements (part of multiple classes)
    df = df[~df["landcover_class"].isnull()]
    df = df.drop(
        df.columns.difference(["geometry", "landcover_class", "highway"]), axis=1
    )

    return df
```

We can then run the plotting code almost like in the example, just creating the aoi polygon manually from the coordinates (could also be handled by the total-bounds of the geometries in the xml, but I think you probably want to set the area you are interested in manually.

```
from prettymapp.geo import get_aoi
from prettymapp.osm import get_osm_geometries
from prettymapp.plotting import Plot
from prettymapp.settings import STYLES
from shapely.geometry import box

aoi = box(118.4862,29.3295,119.2937,29.7644)
df = get_osm_geometries_from_xml(xml_filepath="osmtest.osm", aoi=aoi)

fig = Plot(
    df=df,
    aoi_bounds=aoi.bounds,
    draw_settings=STYLES["Peach"]
).plot_all()
```

The result is rectangular, as the example above doesn't use the `get_aoi` function from the regular example.
<img width="929" alt="image" src="https://github.com/chrieke/prettymapp/assets/12833517/11d4e2dd-879c-417b-abeb-4b9eb8b20881">
Havent integrated it yet, happy for any feedback if you have any before doing so.

**Comment by TheStarAlight** [comment]
wow! That's really nice! I'll have a try on it :D
btw,
> I'm curious if you know if any OSM xml would be like yours, or if that is just specifically via the overpass-api.
I actually can't catch your meaning? Could you pls explain it further?

**Comment by chrieke** [comment]
> I actually can't catch your meaning? Could you pls explain it further?
What I meant is if all "OSM XML" files have this same formatting. To answer my own question after a bit more googling, yes, it's the standard, e.g. when exporting directly from openstreetmap.org.

**Comment by chrieke** [comment]
Added this functionality in release 0.3.0, see the new example in the Readme. Closing this thread.
