### ISSUE TITLE
[bug] requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by clementWedodata** [chrieke/prettymapp#52]
Hi there, 

thank you for this great tool, we wanted to talk about it in our French newsletter dedicated to dataviz (Buena Vista Data Club) but there seems to be a rendering problem when you enter a city other than the examples (cf. screenshot).

Thanks again 🙏

<img width="807" alt="image" src="https://github.com/chrieke/prettymapp/assets/52534300/829ef482-1839-4351-935a-8ee60e0b5c44">

**Comment by chrieke** [comment]
Hey, thank you for the report! Unfortunately I can't recreate the error, "Paris", "paris" or other city names work for me. Could you check again on your side and if the issue still exists share the full error message? Thank you

<img width="833" alt="image" src="https://github.com/chrieke/prettymapp/assets/12833517/a13a08b3-4803-41a8-a905-75148c1fd59c">

**Comment by clementWedodata** [comment]
Hi Christoph, 

Thanks for your feedback. I don't have the bug any more either, it's working again! 
I'll make another ticket if I ever encounter the problem again (with more details).

Thanks again for this great project ;) 

Bye from France
