### ISSUE TITLE
Export geometries as GEOJSON button doesn't work

### ISSUE THREAD

**Issue by LikeAfro** [chrieke/prettymapp#59]
Hi guys. First of all, I say that I love the website. I had planned to download the maps to vectorize them in Adobe Illustrator and make a painting, but when I clicked the export geometries as GEOJSON button, an empty file of 0 bytes was downloaded.
<img width="1282" alt="Captura de pantalla 2024-10-01 a las 21 56 10" src="https://github.com/user-attachments/assets/39219bdd-091e-4a27-b62f-c194c173b675">

**Comment by chrieke** [comment]
Hi @LikeAfro thanks for the report! I think there might have been an isue with the pyogrio depdency, updated it. Seems to work again in the webapp!
