### ISSUE TITLE
Make it easier to customize layer visibility 

### ISSUE THREAD

**Issue by makew0rld** [chrieke/prettymapp#60]
Currently this is the way I'm changing which layers are visible:

```python3
import prettymapp.settings

prettymapp.settings.LC_SETTINGS = {
    "water": {
        "natural": ["water", "bay"],
        "place": ["sea"],
    },
    "woodland": {"landuse": ["forest"]},
    "grassland": {
        "natural": ["island", "wood"],
    },
    "streets": {
        "highway": [
            "motorway",
            "trunk",
            "primary",
            "secondary",
        ],
        "railway": True,
    }
}

from prettymapp.geo import get_aoi
from prettymapp.osm import get_osm_geometries
from prettymapp.plotting import Plot

aoi = get_aoi(address="Toronto, Ontario, Canada", radius=1000, rectangular=True)
df = get_osm_geometries(aoi=aoi)

fig = Plot(
    df=df,
    aoi_bounds=aoi.bounds,
    draw_settings=prettymapp.settings.STYLES["Peach"]
).plot_all()

fig.savefig("map.jpg")
```

This is clunky and not easy to figure out. It would be nice if in the same way I set a custom style with `draw_settings` I could also set a custom layer list as an argument to `get_aoi` or something. Thanks!

**Comment by chrieke** [comment]
Great idea, looking into this now!

**Comment by chrieke** [comment]
Added in verion 0.4.0, you can upgrade via z`pip install prettymapp --upgrade`. Let me know if that goes towards what you imagined. Also see the new Readme chapter on customization.


> You can also customize the selection of OSM landcover classes that should be displayed.
> ```python
> from prettymapp.settings import LANDCOVER_CLASSES
> 
> custom_lc_classes = LANDCOVER_CLASSES.copy()
> custom_lc_classes["urban"]["building"] = False
> 
> df = get_osm_geometries(aoi=aoi, landcover_classes=custom_lc_classes)
> ```

**Comment by makew0rld** [comment]
Thanks! I'm not using prettymapp currently but when/if I use it again I'll let you know if I have any issues.

**Comment by makew0rld** [comment]
@chrieke I'm still seeing some issues with this unfortunately. If for example I copy the existing `LANDCOVER_CLASSES` but rename `urban` to something else like `foo`, then my style for `foo` isn't applied. Using the same trick as my original comment does work.

**Comment by Shrinks99** [comment]
I am also using this library to create some custom styled maps and have run into similar issues when defining street styling as they're all defined under `STREETS_WIDTH` which is hardcoded in `set_geometries`.

https://github.com/chrieke/prettymapp/blob/fb52cfeb62d6a38683be2f06de23ab855a87d3f1/prettymapp/plotting.py#L113C13-L126C69

**Comment by chrieke** [comment]
Reopening, will have a look on weekend.

**Comment by chrieke** [comment]
@makew0rld This should be fixed in https://github.com/chrieke/prettymapp/pull/69 by @C4K3 PR 🙌. Will release a new version in a bit.

@Shrinks99 Will open seperate issue for your request, different topic.
