### ISSUE TITLE
Error running app. - prettymapp.streamlit.app

### ISSUE THREAD

**Issue by sabb1975** [chrieke/prettymapp#65]
![obraz_2024-12-10_190848859](https://github.com/user-attachments/assets/32687240-fdc5-4f09-938a-ba2bfce1d845)

**Comment by mlombardi6** [comment]
It was working for me today, but then it crashed with this same error

**Comment by SollalF** [comment]
Problem is still present today.
I need pretty maps for highly time sensitive secret deep state operations please help fix.
