### ISSUE TITLE
feature request: elevation "iso-lines"

### ISSUE THREAD

**Issue by JulienMaille** [chrieke/prettymapp#67]
Thanks a lot for your work!
I was wondering if there's a way to draw contour lines on the map. It's not clear to me if OpenStreetMap provides elevation data.

**Comment by chrieke** [comment]
Hey, thanks for opening the issue! According to [this](https://gis.stackexchange.com/questions/366487/export-the-contour-lines-of-the-relief-from-osm), the contour lines shown in OSM are based on other datasources. I think they can not be directly queried via the OSM Apis. Also I agree it would be a great feature to have, but including other data sources would probably increase code & usage complexity. This was always intended as a "simple to use" version of the original prettymaps project.

So for todays state have to say this will not be implmented. Thank you for the interesting suggestion!
