### ISSUE TITLE
Provide a way to export and import custom styles

### ISSUE THREAD

**Issue by ypicard** [chrieke/prettymapp#8]
It would be fantastic to be able to export styles and be able to re-import them when coming back to the web application to further work on them.

**Comment by chrieke** [comment]
Great idea, I will look into it! Maybe it can just be a json text field with an export/import button, hidden under an expander.

**Comment by ypicard** [comment]
This would be perfect. Thank you!

**Comment by chrieke** [comment]
Added an export expander to the streamlit app with the relevant parameters of the map configuration in https://github.com/chrieke/prettymapp/pull/19. This doesn't yet allow to reimport the configuration, but think it can still be helpful to have the whole config at one glance and to potentially use with the Python package.

Need to think about a way to enable the import without it becoming too error prone and confusing in the interface for 99% of people who won't use this.

**Comment by chrieke** [comment]
Decided to not add reimporting the configuration, needs to be done manually from the saved configuration, see above.
